Repository openedx/configuration, pull requests merged in 2018-11, with the labels that each got.

#4812 Fix missing boto configuration on GCP VMs for Hawthorn.2
  playbooks/roles/demo/tasks/deploy.yml
  playbooks/roles/edxapp/tasks/deploy.yml
Labels: awaiting prioritization, open-source-contribution

#4869 Fix missing variable `edxapp_app_dir` in demo role
  playbooks/roles/demo/defaults/main.yml
  playbooks/roles/demo/tasks/deploy.yml
Labels: open-source-contribution, waiting on author

#4862 Fix missing boto configuration on GCP VMs (Hawthorn backport)
  playbooks/roles/demo/defaults/main.yml
  playbooks/roles/demo/tasks/deploy.yml
  playbooks/roles/edxapp/tasks/deploy.yml
Labels: awaiting prioritization, open-source-contribution

#4666 Make edx_django_service CONN_MAX_AGE default to 0.
  playbooks/roles/edx_django_service/defaults/main.yml
Labels: engineering review, open-source-contribution

#4880 Avoid running the same operation multiple times
  playbooks/roles/demo/tasks/deploy.yml
Labels: awaiting prioritization, open-source-contribution

#4871 Make sure JWT signing keys are treated as strings.
  playbooks/roles/edx_django_service/defaults/main.yml
  playbooks/roles/edx_notes_api/defaults/main.yml
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution
