Repository openedx/configuration, pull requests merged in 2019-01, with the labels that each got.

#4488 All web pages that contain user-controllable content must opt-out of …
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
Labels: engineering review, open-source-contribution

#4763 Moved Nginx log format name override
  playbooks/roles/nginx/defaults/main.yml
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/xqueue.j2
  playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
Labels: open-source-contribution, waiting on author

#4778 Remove the default edxapp secret key to ensure secure defaults
  CHANGELOG.md
  docker/build/edxapp/ansible_overrides.yml
  playbooks/roles/edxapp/defaults/main.yml
  tests/test_playbooks.sh
Labels: engineering review, open-source-contribution

#4863 Allow installing ecommerce from the custom repo.
  playbooks/roles/ecommerce/defaults/main.yml
  playbooks/roles/ecommerce/meta/main.yml
Labels: awaiting prioritization, open-source-contribution

#4972 Make notifier user service request page size configurable
  playbooks/roles/notifier/defaults/main.yml
Labels: open-source-contribution, waiting on author
