Repository openedx/configuration, pull requests merged in 2019-07, with the labels that each got.

#5196 BB-1372: Add switch to enable/disable data gathering from ec2 instances
  playbooks/roles/aws/defaults/main.yml
  playbooks/roles/aws/tasks/main.yml
  playbooks/roles/edx_service/tasks/main.yml
Labels: open-source-contribution, waiting on author

#5241 Make EDXAPP_PREVIEW_LMS_BASE dynamic for single server native install…
  playbooks/openedx_native.yml
Labels: needs triage, open-source-contribution

#5223 SE-1186 Enhances the analytics_single.yml playbook
  playbooks/analytics_single.yml
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/analytics_api.j2
Labels: awaiting prioritization, open-source-contribution
