Repository openedx/configuration, pull requests merged in 2019-11, with the labels that each got.

#5483 Update labxchange-xblocks to 0.3.0.
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#5488 BB-987: Fix typo on oauth client configuration
  playbooks/roles/oauth_client_setup/defaults/main.yml
Labels: needs triage, open-source-contribution

#5348 CAM2-206 Campus.il Makes the instance types used by asgard configurable
  playbooks/roles/hotg/defaults/main.yml
  playbooks/roles/hotg/meta/main.yml
  playbooks/roles/hotg/templates/edx/app/hotg/Config.groovy.j2
Labels: awaiting prioritization, open-source-contribution

#5501 Fix paypal payment processor default configuration
  CHANGELOG.md
  playbooks/roles/ecommerce/defaults/main.yml
Labels: open-source-contribution, waiting on author

#5416 Allow HTTPS setting to be configured for LMS
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#4844 Security: Prevent the browser from doing MIME-type sniffing
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files.j2
Labels: engineering review, needs triage, open-source-contribution

#4271 Added NGINX_EDXAPP_DEFAULT_SITE_THEME to allow to override favicon wh…
  CHANGELOG.md
  playbooks/roles/nginx/defaults/main.yml
Labels: engineering review, needs triage, open-source-contribution

#4846 Security: Add security-related headers to secure_headers.j2 template
  playbooks/roles/nginx/defaults/main.yml
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/secure_headers.j2
Labels: engineering review, needs triage, open-source-contribution

#4116 Added resolvconf
  playbooks/roles/common_vars/defaults/main.yml
Labels: needs triage, open-source-contribution
