Repository openedx/configuration, pull requests merged in 2020-04, with the labels that each got.

#5704 [BD] Changes for the devstack
  docker/build/analytics_api/analytics_api.yml
  docker/build/analytics_api/ansible_overrides.yml
  docker/build/insights/ansible_overrides.yml
  docker/build/insights/insights.yml
Labels: needs triage, open-source-contribution

#5710 Version bump for LabXchange pathways plugin on edx.org
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#5731 Bump version of LabXchange XBlocks plugin for edx.org (Django 2.2 fix)
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#5755 CRI-171 Makes the forum mongo authentication mechanism configurable
  CHANGELOG.md
  playbooks/roles/forum/defaults/main.yml
Labels: open-source-contribution, waiting on author

#5765 typo fix: respestive -> respective
  playbooks/roles/common/tasks/main.yml
Labels: awaiting prioritization, open-source-contribution
