Repository openedx/configuration, pull requests merged in 2020-07, with the labels that each got.

#5844 Add "| default" filter on AWS_GATHER_FACTS conditional in edx_service
  playbooks/roles/edx_service/tasks/main.yml
Labels: awaiting prioritization, open-source-contribution

#5840 [BD-6] Upgrade packages for python3.8
  playbooks/roles/aws/templates/requirements.txt.j2
  requirements.txt
  requirements/base.in
  requirements/pip-tools.txt
  util/elasticsearch/requirements.txt
  util/jenkins/check_celery_progress/requirements.txt
  util/jenkins/requirements-cloudflare.txt
  util/jenkins/update_celery_monitoring/requirements.txt
  util/pingdom/requirements.txt
  util/vpc-tools/requirements.txt
Labels: needs triage, open-source-contribution

#5847 [BD-6] Change supported python versions in codejail.
  playbooks/roles/codejail/defaults/main.yml
Labels: blended, needs triage

#5856 [BD-6] Update Audio xblock version (Python 3.8 compatible and OEP-18 compliant).
  playbooks/roles/edxapp/defaults/main.yml
Labels: needs triage, open-source-contribution

#5858 [BD-6] Update qualtrics survey xblock version (Python 3.8 compatible and OEP-18 compliant).
  playbooks/roles/edxapp/defaults/main.yml
Labels: blended, needs triage

#5860 [BD-6] Update submit and compare xblock version (Python 3.8 compatible and OEP-18 compliant).
  playbooks/roles/edxapp/defaults/main.yml
Labels: needs triage, open-source-contribution

#5861 [BD-6] Update free text response xblock version (Python 3.8 compatible and OEP-18 compliant).
  playbooks/roles/edxapp/defaults/main.yml
Labels: blended, needs triage

#5863 [BD-6] Update image modal xblock version (Python 3.8 compatible and OEP-18 compliant).
  playbooks/roles/edxapp/defaults/main.yml
Labels: blended, needs triage

#5855 [BD-6] Update Concept xblock version (Python 3.8 compatible and OEP-18 compliant).
  playbooks/roles/edxapp/defaults/main.yml
Labels: needs triage, open-source-contribution

#5862 [BD-6] Update sql grader xblock version (Python 3.8 compatible and OEP-18 compliant).
  playbooks/roles/edxapp/defaults/main.yml
Labels: blended, needs triage

#5854 [BD-6] Update school yourself xblock version (Python 3.8 compatible and OEP-18 compliant)
  playbooks/roles/edxapp/defaults/main.yml
Labels: blended, needs triage

#5866 Remove misleading comment about profile image storage from edxapp role defaults
  playbooks/roles/edxapp/defaults/main.yml
Labels: needs triage, open-source-contribution

#5867 [BD-6] Use pip3 in the Makefile
  Makefile
Labels: blended, needs triage

#5870 Revert "[BD-6] Use pip3 in the Makefile"
  Makefile
Labels: blended, needs triage

#5874 [BD-6] Fix s3 deprecation warning.
  playbooks/roles/go-server/tasks/download_backup.yml
  playbooks/roles/jenkins_admin/tasks/main.yml
Labels: blended, needs triage

#5877 [BD-6] Remove duplicated config in designer role
  playbooks/roles/designer/defaults/main.yml
Labels: blended, needs triage

#5876 [BD-6] Remove duplicated dict key (when).
  playbooks/roles/edx_django_service/tasks/main.yml
Labels: blended, needs triage

#5878 [BD-6] Fix duplicate dict key (owner) warning
  playbooks/roles/gitreload/tasks/course_pull.yml
Labels: needs triage, open-source-contribution

#5757 SE-2298 Makes the ecommerce OSCAR_DEFAULT_CURRENCY configurable.
  playbooks/roles/ecommerce/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#5875 [BD-6] Use latest version of ansible 2.7.*
  requirements.txt
  requirements/base.in
Labels: blended, needs triage

#5697 SE-1983 Campus.il Add newrelic mongo monitoring playbook
  CHANGELOG.md
  playbooks/newrelic_mongo_monitor.yml
  playbooks/roles/mongo_newrelic_monitor/defaults/main.yml
  playbooks/roles/mongo_newrelic_monitor/meta/main.yml
  playbooks/roles/mongo_newrelic_monitor/tasks/main.yml
  playbooks/roles/mongo_newrelic_monitor/templates/mongodb-config.yml.j2
Labels: cc-reviewer, open edx community review, open-source-contribution

#5868 [BD-6] Bootstrap ansible virtualenv with python3.5
  util/install/ansible-bootstrap.sh
Labels: blended, needs triage
