Repository openedx/configuration, pull requests merged in 2020-10, with the labels that each got.

#5837 [BB-2438] Override additional partials and the discussion bootstrap styles to fix styling issues
  playbooks/roles/simple_theme/files/default_skeleton/lms/static/sass/discussion/lms-discussion-bootstrap.scss
  playbooks/roles/simple_theme/files/default_skeleton/lms/static/sass/discussion/lms-discussion-main.scss
  playbooks/roles/simple_theme/files/default_skeleton/lms/static/sass/lms-main-v2.scss
  playbooks/roles/simple_theme/files/default_skeleton/lms/static/sass/partials/lms/theme/_variables-v1.scss
  playbooks/roles/simple_theme/files/default_skeleton/lms/static/sass/partials/lms/theme/_variables.scss
  playbooks/roles/simple_theme/tasks/deploy.yml
Labels: cc-reviewer, open edx community review, open-source-contribution

#6043 Fix issue with `SameSite=None` cookies from being blocked when `django_cookies_samesite.middleware.CookiesSameSite` is enabled for `production` environment.
  playbooks/edxapp.yml
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#6002 Upgrade to ubcpi 1.0.0
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#5992 Created EDXAPP_ variables for all defined FEATURES.
  CHANGELOG.md
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#6053 Save JWT_PUBLIC_SIGNING_JWK_SET as string in ecommerce configurations
  playbooks/roles/ecommerce/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution
