Repository openedx/configuration, pull requests merged in 2020-08, with the labels that each got.

#5896 [BD-6] Add config to deploy registrar with python3.8
  playbooks/roles/registrar/defaults/main.yml
  playbooks/roles/registrar/meta/main.yml
Labels: blended, rejected

#5706 [BB-2217] Allow setting SiteConfiguration values when provisioning an instance
  CHANGELOG.md
  playbooks/roles/edxapp/defaults/main.yml
  playbooks/roles/edxapp/tasks/service_variant_config.yml
  playbooks/roles/edxapp/tasks/site_configuration.yml
  playbooks/roles/edxapp/templates/site_configuration.json.j2
Labels: cc-reviewer, open edx community review, open-source-contribution

#5776 SE-2585 Add systemd override to auto restart mongod
  playbooks/roles/mongo_3_2/files/etc/systemd/system/mongod.service.d/restart.conf
  playbooks/roles/mongo_3_2/tasks/main.yml
Labels: cc-reviewer, open edx community review, open-source-contribution

#5894 [BD-6] Add config to deploy discovery with python3.8
  playbooks/roles/discovery/defaults/main.yml
  playbooks/roles/discovery/meta/main.yml
Labels: blended, needs triage

#5895 [BD-6] Add config to deploy analytics api with python3.8
  playbooks/roles/analytics_api/defaults/main.yml
  playbooks/roles/analytics_api/meta/main.yml
Labels: blended, needs triage

#5897 [BD-6] Add configuration to deploy designer with python3.8
  playbooks/roles/designer/defaults/main.yml
  playbooks/roles/designer/meta/main.yml
Labels: awaiting prioritization, blended

#5899 [BD-06] Add config to deploy enterprise catalog with python3.8
  playbooks/roles/enterprise_catalog/defaults/main.yml
  playbooks/roles/enterprise_catalog/meta/main.yml
Labels: blended, waiting on author

#5900 [BD-06] Add config to deploy blockstore with python3.8
  playbooks/roles/blockstore/defaults/main.yml
  playbooks/roles/blockstore/meta/main.yml
Labels: awaiting prioritization, blended

#5898 [BD-06] Add config to deploy ecommerce with python3.8
  playbooks/roles/ecommerce/defaults/main.yml
  playbooks/roles/ecommerce/meta/main.yml
Labels: blended, waiting on author

#5807 [BB-2447] Add `NGINX_ALLOW_PRIVATE_IP_ACCESS` variable
  CHANGELOG.md
  playbooks/roles/edx_django_service/templates/edx/app/nginx/sites-available/concerns/handle-ip-disclosure.j2
  playbooks/roles/edx_django_service/templates/edx/app/nginx/sites-available/concerns/handle-tls-terminated-elsewhere-ip-disclosure.j2
  playbooks/roles/edx_django_service_with_rendered_config/templates/edx/app/nginx/sites-available/concerns/handle-ip-disclosure.j2
  playbooks/roles/edx_django_service_with_rendered_config/templates/edx/app/nginx/sites-available/concerns/handle-tls-terminated-elsewhere-ip-disclosure.j2
  playbooks/roles/nginx/defaults/main.yml
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/handle-ip-disclosure.j2
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/handle-tls-terminated-elsewhere-ip-disclosure.j2
Labels: cc-reviewer, open edx community review, open-source-contribution

#5922 SE-2989 Update labxchange-xblocks hash to include case study updates
  playbooks/roles/edxapp/defaults/main.yml
Labels: cc-reviewer, open edx community review, open-source-contribution
