Repository openedx/configuration, pull requests merged in 2020-03, with the labels that each got.

#5482 Change Mongo auth_source setting to authsource
  playbooks/roles/edxapp/defaults/main.yml
Labels: blocked by other work, open-source-contribution

#5692 [BD] Install python3 requirements in data api
  playbooks/roles/analytics_api/defaults/main.yml
Labels: needs triage, open-source-contribution

#5693 [BD] Install python3 requirements in Insights
  playbooks/roles/insights/defaults/main.yml
Labels: needs triage, open-source-contribution

#5696 Version bump for LabXchange XBlocks on edx.org
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#5703 [BD] Install insights with python3
  playbooks/roles/insights/defaults/main.yml
  playbooks/roles/insights/tasks/main.yml
Labels: needs triage, open-source-contribution

#5702 [BD] Run analytics api in python3
  playbooks/roles/analytics_api/defaults/main.yml
  playbooks/roles/analytics_api/meta/main.yml
Labels: needs triage, open-source-contribution
