Repository openedx/configuration, pull requests merged in 2020-11, with the labels that each got.

#6044 Fix issue with `SameSite=None` cookies from being blocked when `django_cookies_samesite.middleware.CookiesSameSite` is enabled for `production` environment.
  playbooks/edxapp.yml
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#6127 mariadb: Use a negated "is skipped" check for mariadb_new_debian_cnf
  playbooks/roles/mariadb/tasks/cluster.yml
Labels: awaiting prioritization, open-source-contribution

#6088 Lmm/mfe paths
  playbooks/openedx_native.yml
  playbooks/roles/mfe/defaults/main.yml
  playbooks/roles/mfe/tasks/main.yml
  playbooks/roles/mfe_deployer/defaults/main.yml
  playbooks/roles/mfe_deployer/meta/main.yml
  playbooks/roles/mfe_deployer/tasks/main.yml
  playbooks/roles/mfe_deployer/templates/edx/app/nginx/sites-available/app.j2
  playbooks/roles/mfe_deployer/templates/edx/app/nginx/sites-available/concerns/basic-auth.j2
  playbooks/roles/mfe_deployer/templates/edx/app/nginx/sites-available/concerns/handle-ip-disclosure.j2
  playbooks/roles/mfe_deployer/templates/edx/app/nginx/sites-available/concerns/handle-tls-terminated-elsewhere-ip-disclosure.j2
  playbooks/roles/mfe_deployer/templates/edx/app/nginx/sites-available/concerns/handle-tls-terminated-elsewhere-redirect.j2
  playbooks/roles/mfe_deployer/templates/edx/app/nginx/sites-available/concerns/mfe.j2
  playbooks/roles/mfe_deployer/templates/edx/app/nginx/sites-available/concerns/robots.j2
Labels: open-source-contribution, waiting on author

#6049 MFE role: fix branding override
  CHANGELOG.md
  playbooks/roles/mfe/tasks/main.yml
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/app.j2
Labels: cc-reviewer, open edx community review, open-source-contribution

#6143 [SE-3613] Python2.7 deprecation means htpasswd now requires python3-passlib
  playbooks/roles/nginx/defaults/main.yml
Labels: core committer, open-source-contribution, waiting on author

#6142 mariadb: Use a negated "is skipped" check for mariadb_new_debian_cnf (Juniper)
  playbooks/roles/mariadb/tasks/cluster.yml
Labels: awaiting prioritization, open-source-contribution

#6156 [SE-3613] Install both python-passlib and python3-passlib
  playbooks/roles/nginx/defaults/main.yml
Labels: awaiting prioritization, core committer, open-source-contribution

#6153 allow overriding of nginx max_body_size and proxy_read_timeout
  playbooks/roles/nginx/defaults/main.yml
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/forum.j2
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
Labels: engineering review, open-source-contribution

#6168 doc: Turn user_retirement_pipeline README.rst into actual reST
  playbooks/roles/user_retirement_pipeline/README.rst
Labels: awaiting prioritization, open-source-contribution
