Repository openedx/configuration, pull requests merged in 2020-01, with the labels that each got.

#5590 Allow config of Celery worker prefetch optimization (default|fair)
  CHANGELOG.md
  playbooks/roles/edxapp/defaults/main.yml
  playbooks/roles/edxapp/templates/edx/app/supervisor/conf.d.available/workers.conf.j2
Labels: engineering review, open-source-contribution

#5611 Version bump for LabXchange XBlocks on edx.org
  playbooks/roles/edxapp/defaults/main.yml
Labels: needs triage, open-source-contribution

#5612 Adds a small plugin used by LabXchange.org to implement "pathways"
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#5614 Version bump for LabXchange pathways plugin on edx.org
  playbooks/roles/edxapp/defaults/main.yml
Labels: needs triage, open-source-contribution

#4847 Security: Harden TLS configuration by removing insecure protocol and cyphers
  playbooks/roles/nginx/defaults/main.yml
Labels: needs triage, open-source-contribution

#5527 Make edx_django_service CONN_MAX_AGE configurable via variable for ea…
  playbooks/roles/blockstore/defaults/main.yml
  playbooks/roles/blockstore/meta/main.yml
  playbooks/roles/credentials/defaults/main.yml
  playbooks/roles/credentials/meta/main.yml
  playbooks/roles/designer/defaults/main.yml
  playbooks/roles/designer/meta/main.yml
  playbooks/roles/discovery/defaults/main.yml
  playbooks/roles/discovery/meta/main.yml
  playbooks/roles/ecommerce/defaults/main.yml
  playbooks/roles/ecommerce/meta/main.yml
  playbooks/roles/registrar/defaults/main.yml
  playbooks/roles/registrar/meta/main.yml
  playbooks/roles/veda_web_frontend/defaults/main.yml
  playbooks/roles/veda_web_frontend/meta/main.yml
Labels: awaiting prioritization, open-source-contribution

#5551 SE-1787 Add mongo backups
  playbooks/roles/mongo_3_2/defaults/main.yml
  playbooks/roles/mongo_3_2/tasks/main.yml
  playbooks/roles/mongo_3_2/templates/backup-mongo.sh.j2
  playbooks/roles/mongo_3_2/templates/mongo_logrotate.j2
Labels: awaiting prioritization, open-source-contribution

#5557 Adding additional log format option and reinstates parameter for log format name
  playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
Labels: awaiting prioritization, open-source-contribution
