Repository openedx/configuration, pull requests merged in 2020-09, with the labels that each got.

#5942 [SE-3111] Update labxchange-xblocks audio xBlock
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#5884 [SE-2987] Remove repeated course data dir creation step
  playbooks/roles/edxapp/tasks/main.yml
Labels: awaiting prioritization, open-source-contribution

#5886 Make the special exams toggle configurable
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#6000 Make the special exams toggle configurable (Juniper)
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#5891 Facilitate enabling course export to Git
  playbooks/roles/edxapp/defaults/main.yml
  playbooks/roles/edxapp/tasks/main.yml
Labels: awaiting prioritization, open-source-contribution

#5967 Adding the necessary variables to configure OAuth2 Client
  playbooks/roles/insights/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#5887 Add a toggle for the bulk enrollment view
  playbooks/roles/edxapp/defaults/main.yml
Labels: open-source-contribution, product review

#5958 Add variable for configuring THIRD_PARTY_AUTH_BACKENDS
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#5990 Add EDXAPP_MEDIA_URL to cms nginx configuration.
  CHANGELOG.md
  playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
Labels: engineering review, open-source-contribution

#6032 Facilitate enabling course export to Git (Juniper)
  playbooks/roles/edxapp/defaults/main.yml
  playbooks/roles/edxapp/tasks/main.yml
Labels: needs triage, open-source-contribution

#6031 Add a toggle for the bulk enrollment view (Juniper)
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution

#6014 Fix determining video storage location
  playbooks/roles/edxapp/defaults/main.yml
Labels: engineering review, open-source-contribution

#5951 Use Python 3.8 for `edx-certs`
  CHANGELOG.md
  playbooks/roles/certs/tasks/deploy.yml
  playbooks/roles/certs/tasks/main.yml
Labels: changes requested, open-source-contribution

#6040 Fix ECOMMERCE_USE_PYTHON3 is undefined error
  playbooks/roles/ecommerce/meta/main.yml
Labels: engineering review, open-source-contribution

#6039 Create role to deploy MFE for native installations
  playbooks/openedx_native.yml
  playbooks/roles/mfe/defaults/main.yml
  playbooks/roles/mfe/meta/main.yml
  playbooks/roles/mfe/tasks/main.yml
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/app.j2
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/concerns/basic-auth.j2
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/concerns/handle-ip-disclosure.j2
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/concerns/handle-tls-terminated-elsewhere-ip-disclosure.j2
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/concerns/handle-tls-terminated-elsewhere-redirect.j2
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/concerns/mfe-common.j2
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/concerns/mfe.j2
  playbooks/roles/mfe/templates/edx/app/nginx/sites-available/concerns/robots.j2
  util/install/native.sh
Labels: awaiting prioritization, open-source-contribution

#6046 Fix video storage in juniper
  playbooks/roles/edxapp/defaults/main.yml
Labels: awaiting prioritization, open-source-contribution
