Repository openedx/configuration, pull requests merged in 2021-07, with the labels that each got.

#6449 feature: Allow installing extra requirements when using the `credentials` role
  CHANGELOG.md
  playbooks/roles/credentials/defaults/main.yml
  playbooks/roles/credentials/meta/main.yml
Labels: open-source-contribution, waiting on author

#6467 Unindent a few entries that needd to be unindented (#6450)
  playbooks/roles/edxapp/tasks/deploy.yml
Labels: needs triage, open-source-contribution

#6468 Specify mongo replica set protocolVersion
  playbooks/roles/mongo_4_0/defaults/main.yml
Labels: open-source-contribution, ready to merge

#6456 [SE-4304] Cherry-pick add celerybeat configuration
  playbooks/roles/edxapp/defaults/main.yml
  playbooks/roles/edxapp/tasks/deploy.yml
  playbooks/roles/edxapp/templates/edx/app/edxapp/beat_scheduler.sh.j2
  playbooks/roles/edxapp/templates/edx/app/supervisor/conf.d.available/workers.conf.j2
Labels: open-source-contribution, ready to merge

#6483 [FAL-2000] Remove jdk role from openedx-native playbook and elasticsearch role dependencies
  playbooks/openedx_native.yml
  playbooks/roles/elasticsearch/meta/main.yml
  playbooks/roles/elasticsearch/tasks/main.yml
Labels: changes requested, open-source-contribution

#6482 [SE-4612] Update elasticsearch configurations
  playbooks/roles/elasticsearch/defaults/main.yml
  playbooks/roles/elasticsearch/tasks/main.yml
  playbooks/roles/elasticsearch/templates/edx/etc/elasticsearch/elasticsearch.yml.j2
  playbooks/roles/elasticsearch/templates/edx/etc/elasticsearch/jvm.options.j2
  playbooks/roles/elasticsearch/templates/edx/etc/elasticsearch/logging.yml.j2
  playbooks/roles/elasticsearch/templates/etc/default/elasticsearch.j2
  playbooks/roles/elasticsearch/templates/lib/systemd/system/elasticsearch.service.j2
Labels: awaiting prioritization, open-source-contribution

#6489 [BB-3801] feat: allow writing extra requirements to a requirements file
  CHANGELOG.md
  playbooks/roles/ecommerce/defaults/main.yml
  playbooks/roles/ecommerce/meta/main.yml
  playbooks/roles/edx_django_service/tasks/main.yml
Labels: awaiting prioritization, open-source-contribution

#6479 Specify mongo replica set protocolVersion.
  playbooks/roles/mongo_4_0/defaults/main.yml
Labels: open-source-contribution, waiting on author
