Repository openedx/configuration, pull requests merged in 2021-04, with the labels that each got.

#6358 fix: allow mfe_deployer to run
  playbooks/openedx_native.yml
Labels: engineering review, open-source-contribution

#6369 fix: allow mfe_deployer to run
  playbooks/openedx_native.yml
Labels: needs triage, open-source-contribution

#6376 fix: mysql 5.7 issue
  playbooks/roles/mysql/defaults/main.yml
Labels: cc-reviewer, needs triage, open-source-contribution

#6378 fix: mysql 5.7 issue
  playbooks/roles/mysql/defaults/main.yml
Labels: cc-reviewer, needs triage, open-source-contribution

#6377 fix: mysql 5.7 issue
  playbooks/roles/mysql/defaults/main.yml
Labels: cc-reviewer, needs triage, open-source-contribution

#6383 fix: exit with ansible exit code.
  util/install/native.sh
Labels: needs triage, open-source-contribution
