Repository openedx/configuration, pull requests merged in 2021-01, with the labels that each got.

#6171 Add Documentation to the mfe_deployer role
  playbooks/roles/mfe/README.rst
  playbooks/roles/mfe_deployer/README.rst
Labels: cc-reviewer, open edx community review, open-source-contribution

#6179 [SE-3381] Allows adding new tinymce plugins through platform configuration
  CHANGELOG.md
  playbooks/roles/edxapp/tasks/deploy.yml
  playbooks/roles/tinymce_plugins/README.rst
  playbooks/roles/tinymce_plugins/defaults/main.yml
  playbooks/roles/tinymce_plugins/tasks/import_tinymce_plugin.yml
  playbooks/roles/tinymce_plugins/tasks/main.yml
  playbooks/roles/tinymce_plugins/tasks/rebuild_tinymce_files.yml
Labels: cc-reviewer, open-source-contribution, ready to merge

#6244 Rename rebuild_index to rebuild_indices, as used in forum
  playbooks/roles/forum/tasks/deploy.yml
Labels: needs triage, open-source-contribution

#6251 postfix_queue: Add the ability to set recipient canonical maps
  playbooks/roles/postfix_queue/defaults/main.yml
  playbooks/roles/postfix_queue/tasks/main.yml
Labels: awaiting prioritization, open-source-contribution

#6264 postfix_queue: Add the ability to set recipient canonical maps
  playbooks/roles/postfix_queue/defaults/main.yml
  playbooks/roles/postfix_queue/tasks/main.yml
Labels: awaiting prioritization, open-source-contribution
