Repository openedx/configuration, pull requests merged in 2021-08, with the labels that each got.

#6462 FAL-2077 add ansible tasks to init mongodb indexes
  CHANGELOG.md
  playbooks/roles/edxapp/defaults/main.yml
  playbooks/roles/edxapp/tasks/deploy.yml
  playbooks/roles/forum/defaults/main.yml
  playbooks/roles/forum/tasks/deploy.yml
Labels: cc-reviewer, engineering review, open-source-contribution

#6487 feat: Improve blockstore deployment
  playbooks/roles/blockstore/defaults/main.yml
  playbooks/roles/blockstore/meta/main.yml
Labels: awaiting prioritization, open-source-contribution

#6524 fix: removes certs from list of nginx sites
  playbooks/openedx_native.yml
Labels: open-source-contribution, core committer

#6520 Enforcing read committed isolation level for edxapp MySQL database
  playbooks/roles/edxapp/defaults/main.yml
Labels: open-source-contribution, awaiting prioritization
