Repository openedx/configuration, pull requests merged in 2022-01, with the labels that each got.

#6646 fix: add Elasticsearch variable overrides
  CHANGELOG.md
  playbooks/roles/discovery/defaults/main.yml
  playbooks/roles/edx_notes_api/defaults/main.yml
Labels: open-source-contribution, needs triage, cc-reviewer

#6659 lilac backport: add Elasticsearch variable overrides
  CHANGELOG.md
  playbooks/roles/discovery/defaults/main.yml
  playbooks/roles/edx_notes_api/defaults/main.yml
Labels: open-source-contribution, awaiting prioritization

#6660 maple backport: add Elasticsearch variable overrides
  CHANGELOG.md
  playbooks/roles/discovery/defaults/main.yml
  playbooks/roles/edx_notes_api/defaults/main.yml
Labels: open-source-contribution, awaiting prioritization

#6665 Upgrade devpi versions for devstack Docker container
  docker/build/devpi/Dockerfile
  docker/build/devpi/docker-entrypoint.sh
Labels: automerge
