Repository openedx/configuration, pull requests merged in 2022-04, with the labels that each got.

#6685 feat: add nginx server names hash override [BB-5512]
  playbooks/roles/nginx/defaults/main.yml
  playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
Labels: open-source-contribution, ready to merge, automerge

#6686 feat: add nginx server names hash override [BB-5512]
  playbooks/roles/nginx/defaults/main.yml
  playbooks/roles/nginx/templates/etc/nginx/nginx.conf.j2
Labels: open-source-contribution, ready to merge, automerge

#6706 feat: added new setting CUSTOM_RESOURCE_TEMPLATES_DIRECTORY
  CHANGELOG.md
  playbooks/roles/edxapp/defaults/main.yml
Labels: open-source-contribution, awaiting prioritization

#6679 feat: add SIMPLETHEME_I18N_DJANGO variable
  CHANGELOG.md
  playbooks/roles/simple_theme/defaults/main.yml
  playbooks/roles/simple_theme/tasks/deploy.yml
  playbooks/roles/simple_theme/templates/i18n/domain.po.j2
Labels: open-source-contribution, changes requested

#6708 feat: optionally collect JS translations on deploy
  CHANGELOG.md
  playbooks/roles/edxapp/defaults/main.yml
  playbooks/roles/edxapp/tasks/deploy.yml
Labels: open-source-contribution, awaiting prioritization
